
var cgen = require('./cgen');
var fs = require('fs');
var assert = require('assert');
var util = require('util');

describe('CodeGen', function() {
  it('should work', function() {
    var files = new cgen.FileGen('/tmp/');
    var cg = files.getFile('cgen_test.h');
    var o = cg.child({XXX: '37'});
    o('int test1() {');
    o('return 7 + XXX;');
    o('while (1) {}');
    o('foo(1,');
    o('2,3);');
    o('}');
    cg.end();

    var l = fs.readFileSync('/tmp/cgen_test.h', 'utf8');
    assert.ok(/define INCLUDE__tmp_cgen_test_h/.test(l));
    assert.ok(/Generated by/.test(l));
    assert.ok(/return 7 \+ 37/.test(l));
  });
});
