
const cgen = require('./cgen');
const fs = require('fs');
const assert = require('assert');
const util = require('util');

describe('CodeGen', function() {
  it('should work', function() {
    let files = new cgen.FileGen('/tmp/');
    let cg = files.getFile('cgen_test.h');
    let o = cg.child({XXX: '37'});
    o(`
      int test1() {
        return 7 + XXX;
        while (1) {}
        foo(1,
          2,3);
        }
    `);
    cg.end();

    let l = fs.readFileSync('/tmp/cgen_test.h', 'utf8');
    assert.ok(/define INCLUDE__tmp_cgen_test_h/.test(l));
    assert.ok(/Generated by/.test(l));
    assert.ok(/return 7 \+ 37/.test(l));
  });
});
