/* Generated by node /Users/tlb/tlbcore/code_gen/mk_marshall.js geom/decl_geom.js numerical/decl_numerical.js at Fri, 14 Feb 2014 02:48:35 GMT */
#ifndef INCLUDE_arma_jswrap_h
#define INCLUDE_arma_jswrap_h

#include <armadillo>

typedef JsWrapGeneric< arma::mat > JsWrap_mat;

typedef JsWrapGeneric< arma::vec > JsWrap_vec;

Handle<Value> jsConstructor_mat(JsWrap_mat *it, const Arguments &args);
Handle<Value> jsConstructor_vec(JsWrap_vec *it, const Arguments &args);

#endif
